// <auto-generated />
using System;
using ComputerManagerApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ComputerManagerApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260508000000_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // ComponentManufacturers
            modelBuilder.Entity("ComputerManagerApi.Models.ComponentManufacturer", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("Abbreviation").IsRequired().HasMaxLength(30).HasColumnType("nvarchar(30)");
                b.Property<DateOnly>("FoundationDate").HasColumnType("date");
                b.Property<string>("FullName").IsRequired().HasMaxLength(300).HasColumnType("nvarchar(300)");
                b.HasKey("Id");
                b.ToTable("ComponentManufacturers");
                b.HasData(
                    new { Id = 1, Abbreviation = "AMD",  FoundationDate = new DateOnly(1969, 5, 1),  FullName = "Advanced Micro Devices"  },
                    new { Id = 2, Abbreviation = "NV",   FoundationDate = new DateOnly(1993, 4, 5),  FullName = "NVIDIA Corporation"       },
                    new { Id = 3, Abbreviation = "COR",  FoundationDate = new DateOnly(1994, 1, 1),  FullName = "Corsair Gaming Inc."      },
                    new { Id = 4, Abbreviation = "ASUS", FoundationDate = new DateOnly(1989, 4, 2),  FullName = "ASUSTeK Computer Inc."   });
            });

            // ComponentTypes
            modelBuilder.Entity("ComputerManagerApi.Models.ComponentType", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("Abbreviation").IsRequired().HasMaxLength(30).HasColumnType("nvarchar(30)");
                b.Property<string>("Name").IsRequired().HasMaxLength(150).HasColumnType("nvarchar(150)");
                b.HasKey("Id");
                b.ToTable("ComponentTypes");
                b.HasData(
                    new { Id = 1, Abbreviation = "CPU", Name = "Processor"          },
                    new { Id = 2, Abbreviation = "GPU", Name = "Graphics Card"      },
                    new { Id = 3, Abbreviation = "RAM", Name = "Memory"             },
                    new { Id = 4, Abbreviation = "SSD", Name = "Solid State Drive"  });
            });

            // Components
            modelBuilder.Entity("ComputerManagerApi.Models.Component", b =>
            {
                b.Property<string>("Code").HasMaxLength(10).HasColumnType("char(10)");
                b.Property<int>("ComponentManufacturersId").HasColumnType("int");
                b.Property<int>("ComponentTypesId").HasColumnType("int");
                b.Property<string>("Description").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("Name").IsRequired().HasMaxLength(300).HasColumnType("nvarchar(300)");
                b.HasKey("Code");
                b.HasIndex("ComponentManufacturersId");
                b.HasIndex("ComponentTypesId");
                b.ToTable("Components");
                b.HasData(
                    new { Code = "CPU0000001", ComponentManufacturersId = 1, ComponentTypesId = 1, Description = "8-core gaming processor with 3D V-Cache technology",    Name = "Ryzen 7 7800X3D"             },
                    new { Code = "GPU0000001", ComponentManufacturersId = 2, ComponentTypesId = 2, Description = "High-end gaming graphics card with 16 GB GDDR6X",       Name = "RTX 4080 Super"              },
                    new { Code = "RAM0000001", ComponentManufacturersId = 3, ComponentTypesId = 3, Description = "DDR5 RAM module 16GB 5200 MHz",                          Name = "Corsair Vengeance DDR5 16GB" },
                    new { Code = "SSD0000001", ComponentManufacturersId = 4, ComponentTypesId = 4, Description = "NVMe PCIe 4.0 SSD 1TB with 7000 MB/s read speed",       Name = "ASUS ROG Strix SSD 1TB"      });
            });

            // PCs
            modelBuilder.Entity("ComputerManagerApi.Models.Pc", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<string>("Name").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<int>("Stock").HasColumnType("int");
                b.Property<int>("Warranty").HasColumnType("int");
                b.Property<double>("Weight").HasColumnType("float");
                b.HasKey("Id");
                b.ToTable("PCs");
                b.HasData(
                    new { Id = 1, CreatedAt = new DateTime(2026, 5,  8, 9,  0, 0), Name = "Gaming Beast X",    Stock = 5,  Warranty = 36, Weight = 12.5 },
                    new { Id = 2, CreatedAt = new DateTime(2026, 4, 15, 13, 30, 0), Name = "Office Mini Pro",  Stock = 12, Warranty = 24, Weight = 4.2  },
                    new { Id = 3, CreatedAt = new DateTime(2026, 3,  1, 10,  0, 0), Name = "Workstation Ultra",Stock = 3,  Warranty = 48, Weight = 9.8  });
            });

            // PCComponents
            modelBuilder.Entity("ComputerManagerApi.Models.PcComponent", b =>
            {
                b.Property<int>("PcId").HasColumnType("int");
                b.Property<string>("ComponentCode").HasMaxLength(10).HasColumnType("char(10)");
                b.Property<int>("Amount").HasColumnType("int");
                b.HasKey("PcId", "ComponentCode");
                b.HasIndex("ComponentCode");
                b.ToTable("PCComponents");
                b.HasData(
                    new { PcId = 1, ComponentCode = "CPU0000001", Amount = 1 },
                    new { PcId = 1, ComponentCode = "GPU0000001", Amount = 1 },
                    new { PcId = 1, ComponentCode = "RAM0000001", Amount = 2 },
                    new { PcId = 2, ComponentCode = "CPU0000001", Amount = 1 },
                    new { PcId = 2, ComponentCode = "RAM0000001", Amount = 1 },
                    new { PcId = 2, ComponentCode = "SSD0000001", Amount = 1 },
                    new { PcId = 3, ComponentCode = "CPU0000001", Amount = 2 },
                    new { PcId = 3, ComponentCode = "RAM0000001", Amount = 4 },
                    new { PcId = 3, ComponentCode = "SSD0000001", Amount = 2 });
            });

            // Relationships
            modelBuilder.Entity("ComputerManagerApi.Models.Component", b =>
            {
                b.HasOne("ComputerManagerApi.Models.ComponentManufacturer", "Manufacturer")
                 .WithMany("Components").HasForeignKey("ComponentManufacturersId")
                 .OnDelete(DeleteBehavior.Restrict).IsRequired();
                b.HasOne("ComputerManagerApi.Models.ComponentType", "Type")
                 .WithMany("Components").HasForeignKey("ComponentTypesId")
                 .OnDelete(DeleteBehavior.Restrict).IsRequired();
                b.Navigation("Manufacturer");
                b.Navigation("Type");
            });

            modelBuilder.Entity("ComputerManagerApi.Models.PcComponent", b =>
            {
                b.HasOne("ComputerManagerApi.Models.Component", "Component")
                 .WithMany("PcComponents").HasForeignKey("ComponentCode")
                 .OnDelete(DeleteBehavior.Restrict).IsRequired();
                b.HasOne("ComputerManagerApi.Models.Pc", "Pc")
                 .WithMany("PcComponents").HasForeignKey("PcId")
                 .OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.Navigation("Component");
                b.Navigation("Pc");
            });

            modelBuilder.Entity("ComputerManagerApi.Models.ComponentManufacturer", b => b.Navigation("Components"));
            modelBuilder.Entity("ComputerManagerApi.Models.ComponentType",         b => b.Navigation("Components"));
            modelBuilder.Entity("ComputerManagerApi.Models.Component",             b => b.Navigation("PcComponents"));
            modelBuilder.Entity("ComputerManagerApi.Models.Pc",                    b => b.Navigation("PcComponents"));
#pragma warning restore 612, 618
        }
    }
}
